openapi: 3.1.0
info:
  version: 1.0.0
  title: My movies app
  license:
    name: Apache 2.0
    url: <http://www.apache.org/licenses/LICENSE-2.0.html>
  description: >
    This is a documentation of my movies app
tags:
  - name: Movies
    description: Operations about movies.
  - name: Auth
    description: Auth operations.
servers:
  - url: <http://localhost:3000>
  - url: <https://example.com/api/v1>
paths:
    /api/movies:
      get:
        $ref: ../swagger/paths/movies/get.yaml
      post:
        $ref: ../swagger/paths/movies/post.yaml
    /api/movies/{id}:
      get:
        $ref: ../swagger/paths/movies/{id}/get.yaml

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
